name: task_1_crud_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  dio: ^5.4.0
  retrofit: ^4.0.3
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  retrofit_generator: ^8.0.6
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  

flutter:
  uses-material-design: true
  assets:
    - assets/bg.jpg
